-- =============================================================================
-- 102_ann_rule_engine.sql — 공고 자격판정을 LLM 없이 하는 층
--
--   왜 만드나
--     지금 판정은 전부 LLM 이다(bot/gongo.py PROMPT_SCORE). 그런데 실측을 보면
--     **LLM 경로는 836건을 감당하지 못한다** — 호출당 약 4만 토큰이라 37건에서
--     멈춰 있고(가능 1 · 불가 15 · 확인필요 21), 본문이 없는 764건은 손도 못 댔다.
--     그래서 이건 「비용 절약」이 아니라 **커버리지 확장**이다: 제목·지역코드·
--     지원대상·접수종료만으로도 게이트 판정이 되는 공고가 대다수다.
--
--   설계 원칙 — CLAUDE.md §6 을 그대로 따른다
--     ① 계산으로 확정되는 것은 LLM 에게 맡기지 않는다.
--        마감일 지남 · 지역 불일치 · 지원대상 불일치는 **계산이다.** 모델에게 묻지 않는다.
--     ② 모르면 모른다고 한다. 본문이 없어 조항을 못 읽었으면 「불가」가 아니라
--        **「요건미확인」**이다. 「불가」로 잘못 찍으면 그 공고는 조용히 버려진다.
--     ③ 수치를 지어내지 않는다. 추출한 특징마다 **근거문장을 원문 그대로** 남기고
--        원문 안 위치(문자 offset)까지 적는다. 근거가 없는 특징은 저장되지 않는다.
--     ④ 회사 정보에 없는 값이 필요한 조건은 점수를 깎지 않는다 — 확인필요항목으로
--        올린다. 모르는 것을 불리하게 보지 않는다(PROMPT_SCORE 규칙 2번과 같다).
--
--   기존 것을 건드리지 않는다
--     app.eligibility_decisions(LLM 판정 + 사람 정정 이력)는 **손대지 않는다.**
--     ALTER 로 컬럼을 붙이면 ⓐ 소유자 문제(기존 테이블은 supabase_admin 소유라 막힌다)
--     ⓑ LLM 판정과 규칙 판정이 한 행에 섞여 **섀도 대조를 못 한다.**
--     → 규칙 판정은 곁 테이블 app.ann_rule_scores 에 따로 쌓고, 뷰에서 나란히 놓는다.
--
--   적용:     cd /web/rnd && ./db/psql.sh -f db/102_ann_rule_engine.sql
--   되돌리기: 파일 맨 아래 블록
-- =============================================================================

begin;

-- -----------------------------------------------------------------------------
-- 1. 추출된 특징 — 「공고문이 무엇을 요구하는가」를 한 줄씩 쪼개 둔다
--
--    한 공고 = 여러 행. 규칙마다 한 행이라 **어느 규칙이 무엇을 근거로 뽑았는지**가
--    행 단위로 남는다. 판정이 틀렸을 때 프롬프트를 노려보는 대신 규칙id 를 찾는다.
-- -----------------------------------------------------------------------------
create table if not exists app.ann_features (
  id               bigint generated by default as identity primary key,
  announcement_id  bigint not null references app.announcements(id) on delete cascade,
  특징키           text not null,
  종류             text not null,      -- 게이트 | 가산 | 정보
  값_텍스트        text,
  값_수치          numeric,
  값_불리언        boolean,
  단위             text,
  구역             text,               -- 신청자격 | 지원제외 | 제출서류 | 지원규모 | 메타 | 미상
  근거문장         text,
  근거_위치        integer,            -- 원문 안 문자 offset. null 이면 본문이 아니라 메타에서 왔다
  규칙id           text not null,
  규칙신뢰도       numeric(4,3) not null,
  추출원           text not null,      -- 메타 | 본문 | 렉시콘 | 사람
  엔진버전         text not null,
  created_at       timestamptz not null default now(),
  unique (announcement_id, 특징키, 규칙id, 엔진버전)
);

create index if not exists idx_annfeat_공고 on app.ann_features (announcement_id);
create index if not exists idx_annfeat_키   on app.ann_features (특징키);

comment on table app.ann_features is
  '공고문에서 규칙(정규식·구역 인식)으로 뽑은 자격요건 특징. LLM 을 쓰지 않는다. '
  '근거문장·근거_위치가 없으면 저장하지 않는다 — 지어낸 특징이 들어올 자리를 구조적으로 없앤다.';
comment on column app.ann_features.구역 is
  '공고문 안 어느 절에서 나왔는가. 같은 문구가 「신청자격」에 있을 때와 「지원제외」에 '
  '있을 때 뜻이 반대다. 구역을 모르면 규칙이 오탐한다.';
comment on column app.ann_features.추출원 is
  '메타=API 가 준 컬럼(지역코드·지원대상·접수종료) · 본문=정규식 · 렉시콘=사람 정정에서 배운 패턴 · 사람=직접 답변.';
comment on column app.ann_features.규칙신뢰도 is
  '규칙 자체의 신뢰도(패턴이 얼마나 특정적인가). 사람 확인으로 갱신될 자리다. '
  '판정 확신도는 이 값들과 커버리지로 계산한다 — 모델이 자기 확신도를 말하게 하지 않는다.';

-- -----------------------------------------------------------------------------
-- 2. 규칙 판정 결과 — LLM 판정(eligibility_decisions)과 **따로** 쌓는다
--
--    엔진버전으로 세대를 구분한다. 규칙을 고친 뒤 같은 공고를 다시 판정해도
--    이전 판정이 남아 있어야 「고쳐서 나아졌는가」를 말할 수 있다.
-- -----------------------------------------------------------------------------
create table if not exists app.ann_rule_scores (
  id               bigint generated by default as identity primary key,
  announcement_id  bigint not null references app.announcements(id) on delete cascade,
  엔진버전         text not null,
  점수             integer not null,
  판정             text not null,      -- 가능 | 불가 | 확인필요 | 요건미확인
  확신도           numeric(4,3) not null,
  커버리지         numeric(4,3) not null,   -- 판정에 필요한 특징 중 실제로 확보한 비율
  판정경로         text not null,      -- 규칙 | 규칙+사람 | LLM폴백
  게이트_결과      jsonb not null default '[]'::jsonb,   -- [{키,통과,사유,근거}]
  특징_기여        jsonb not null default '[]'::jsonb,   -- [{키,가중치,점수,근거}]
  확인필요항목     text[] not null default '{}',
  근거             text[] not null default '{}',
  llm_호출         integer not null default 0,   -- 이 판정에 쓴 LLM 호출 수. 규칙 경로는 0 이다
  ms               integer,
  created_at       timestamptz not null default now(),
  unique (announcement_id, 엔진버전),
  constraint chk_rule_판정
    check (판정 in ('가능', '불가', '확인필요', '요건미확인')),
  constraint chk_rule_경로
    check (판정경로 in ('규칙', '규칙+사람', 'LLM폴백'))
);

create index if not exists idx_annrule_판정 on app.ann_rule_scores (판정);
create index if not exists idx_annrule_공고 on app.ann_rule_scores (announcement_id);

comment on table app.ann_rule_scores is
  '규칙 엔진 자격판정. llm_호출=0 인 행이 「LLM 없이 판정한 건」이다 — 화면의 지표가 이 컬럼에서 나온다. '
  'LLM 판정(app.eligibility_decisions)은 건드리지 않고 따로 쌓아 v_ann_rule_vs_llm 에서 나란히 대조한다.';
comment on column app.ann_rule_scores.커버리지 is
  '판정에 필요한 특징 중 실제로 확보한 비율. 낮으면 점수를 매기지 않고 「요건미확인」으로 둔다 — '
  '조항을 못 읽은 것을 「불가」로 찍으면 그 공고는 조용히 버려진다(§6 설계 원칙 4번).';

-- -----------------------------------------------------------------------------
-- 3. 사람 답변 — 규칙이 못 정하면 **사람에게 묻고, 답을 자산으로 쌓는다**
--
--    「확인해보세요」가 아니라 근거문장을 인용한 구체적인 질문을 만든다.
--    일반화=true 인 답은 회사 상수로 승격돼 다음 공고에서 다시 묻지 않는다.
--    이게 「쌓으면 LLM 없이도 판단이 된다」의 실제 메커니즘이다.
-- -----------------------------------------------------------------------------
create table if not exists app.ann_feature_answers (
  id               bigint generated by default as identity primary key,
  announcement_id  bigint references app.announcements(id) on delete cascade,  -- null = 공고와 무관한 회사 상수
  특징키           text not null,
  질문             text not null,
  근거문장         text,               -- 물을 때 보여준 공고문 원문. 답의 맥락이다
  ai_추출값        text,               -- 규칙이 뽑아둔 값. 사람이 이것을 고쳤다면 정정 이력이 된다
  사람_값          text not null,      -- 예 | 아니오 | 모름 | 자유값
  사유             text,
  일반화           boolean not null default false,
  답변자           text not null,
  created_at       timestamptz not null default now()
);

create index if not exists idx_annans_공고 on app.ann_feature_answers (announcement_id);
create index if not exists idx_annans_키   on app.ann_feature_answers (특징키);

comment on table app.ann_feature_answers is
  '규칙이 못 정한 요건에 사람이 준 답. 일반화=true 면 공고를 넘어 회사 상수로 쓴다(설립일·업력 등). '
  'ai_추출값과 사람_값이 다르면 그 자체가 정정 이력이다 — extraction_lexicon 이 여기서 나온다.';
comment on column app.ann_feature_answers.일반화 is
  'true = 이 답은 이 공고만의 사정이 아니라 회사에 대한 사실이다. 다음 공고에서 다시 묻지 않는다. '
  'false = 이 공고 한정. 다른 공고에 옮겨 쓰면 틀린 판정이 된다.';

-- -----------------------------------------------------------------------------
-- 4. 학습된 추출 패턴 — 사람 정정에서 자란다
--
--    규칙이 못 뽑은 문구를 사람이 짚어주면 (문구 → 특징키·값) 매핑이 여기 쌓인다.
--    다음 판독은 정규식보다 **먼저** 이 표를 본다. 표가 자라면 LLM 폴백이 줄어든다.
--    벡터 DB 를 넣지 않는다(CLAUDE.md §7) — 부분문자열·정규식으로 충분하다.
-- -----------------------------------------------------------------------------
create table if not exists app.extraction_lexicon (
  id               bigint generated by default as identity primary key,
  패턴             text not null,      -- 공고문에 실제로 있던 문구(또는 정규식)
  패턴유형         text not null default '부분문자열',  -- 부분문자열 | 정규식
  특징키           text not null,
  종류             text not null,      -- 게이트 | 가산 | 정보
  값_텍스트        text,
  값_수치          numeric,
  값_불리언        boolean,
  구역             text,               -- 이 구역에서만 적용. null 이면 어디서든
  신뢰도           numeric(4,3) not null default 0.900,
  출처_answer_id   bigint references app.ann_feature_answers(id) on delete set null,
  만든이           text not null,
  적용횟수         integer not null default 0,
  적중_확인        integer not null default 0,   -- 적용 후 사람이 맞다고 한 횟수
  적중_반박        integer not null default 0,   -- 적용 후 사람이 틀렸다고 한 횟수
  사용중           boolean not null default true,
  created_at       timestamptz not null default now(),
  unique (패턴, 특징키, 구역)
);

comment on table app.extraction_lexicon is
  '사람 정정에서 배운 문구→특징 매핑. 규칙 엔진이 정규식보다 먼저 본다. '
  '적중_확인/적중_반박 이 쌓이면 신뢰도를 근거 있게 조정할 수 있다 — 지금은 지어내지 않고 기본값으로 둔다.';

-- -----------------------------------------------------------------------------
-- 5. 점수 가중치 — 코드가 아니라 데이터다
--
--    가중치를 코드에 박으면 고칠 때마다 배포해야 하고, 「왜 이 점수인가」가
--    파일 안에 숨는다. funding_schemes.대분류 를 데이터로 둔 것과 같은 이유다.
--
--    ⚠ 초기값은 **PROMPT_SCORE 의 규칙을 그대로 옮긴 것**이다. 라벨이 37건뿐이라
--      학습으로 맞추면 과적합이고, 그 수치는 시연에서 근거로 쓸 수 없다.
--      학습 훅(ann_feature_answers·extraction_lexicon)은 심어두고, 지금 내세우는
--      근거는 v_ann_rule_vs_llm 의 **실측 일치율**이다.
-- -----------------------------------------------------------------------------
create table if not exists app.scoring_weights (
  특징키           text primary key,
  종류             text not null,      -- 게이트 | 가산 | 정보
  가중치           numeric not null default 0,
  설명             text not null,
  회사컬럼         text,               -- 대조할 company_profile 컬럼. null 이면 공고문만 본다
  필수_커버리지    boolean not null default false,  -- 커버리지 계산에 넣을 특징인가
  updated_at       timestamptz not null default now()
);

comment on table app.scoring_weights is
  '자격판정 점수 가중치. 게이트는 가중치를 쓰지 않고 통과/탈락만 본다 — 게이트는 계산이다. '
  '초기값은 bot/gongo.py PROMPT_SCORE 의 규칙을 코드로 옮긴 것이고, 학습으로 갱신될 자리다.';

insert into app.scoring_weights (특징키, 종류, 가중치, 설명, 회사컬럼, 필수_커버리지) values
  -- ── 게이트: 어긋나면 즉시 「불가」. 계산으로 확정되므로 LLM 에게 묻지 않는다 ──
  ('접수마감',            '게이트',  0, '접수종료가 오늘보다 앞이면 신청할 수 없다. 날짜 비교다.', null, true),
  ('지역제한',            '게이트',  0, '공고 지역코드에 우리 지역도 「전국」도 없으면 불가. 배열 교집합이다.', '지역코드', true),
  ('지원대상_유형',       '게이트',  0, '지원대상에 기업 계열 토큰이 하나도 없으면(개인·학생·기관 전용) 불가.', '지원대상_유형', true),
  ('자본전액잠식_제외',   '게이트',  0, '공고에 자본전액잠식 제외 조항이 있고 우리가 잠식 상태면 불가.', '자본전액잠식', false),
  ('부채비율_상한',       '게이트',  0, '공고가 제시한 부채비율 상한을 우리 부채비율이 넘으면 불가. 모르면 확인필요.', '부채비율', false),
  ('기업부설연구소_필수', '게이트',  0, '연구소 보유가 신청자격이면 미보유는 불가. 보유면 가산으로도 잡힌다.', '기업부설연구소', false),
  ('기업규모_제한',       '게이트',  0, '중견 이상 전용 등 우리 기업규모를 배제하는 조항.', '기업규모', false),
  -- ── 가산: 기본 50점에서 올린다. 합이 50 을 넘지 않게 둔다 ──
  ('업종적합도',          '가산',   20, '공고 사업명·지원분야가 우리 업종·주요제품 어휘와 겹치는 정도.', '업종명', true),
  ('지원분야_기술',       '가산',   10, '지원분야가 기술·기술개발(R&D)이면 우리 성격에 맞는다.', null, true),
  ('연구소_보유가점',     '가산',    8, '기업부설연구소 보유를 자격·가점으로 요구하고 우리가 보유한 경우.', '기업부설연구소', false),
  ('지역_우리지역명시',   '가산',    7, '「전국」이 아니라 우리 지역을 콕 집은 공고. 경쟁 모수가 작다.', '지역코드', false),
  ('대상_중소기업명시',   '가산',    5, '지원대상에 중소기업이 명시된 경우.', '지원대상_유형', false),
  -- ── 정보: 점수에 넣지 않는다. 화면과 질문 생성에 쓴다 ──
  ('지원금액',            '정보',    0, '공고가 밝힌 지원 한도·총사업비. 단위를 환산하지 않고 원문 그대로 둔다.', null, false),
  ('자기부담률',          '정보',    0, '자부담·기관부담 비율. 재원 분담 화면이 쓴다.', null, false),
  ('업력_제한',           '정보',    0, '창업 N년 이내 같은 업력 조건. 설립일이 없으면 확인필요로 올린다.', '설립일', false),
  ('매출액_기준',         '정보',    0, '매출액 상·하한 조건. 우리 매출액이 비어 있으면 확인필요로 올린다.', '매출액', false),
  ('종업원수_기준',       '정보',    0, '종업원수 조건. 비어 있으면 확인필요로 올린다.', '종업원수', false),
  ('법인사업자_필수',     '정보',    0, '개인사업자를 배제하는 조항. 우리는 법인이나 서류로 확인해야 한다.', null, false),
  ('체납_제외',           '정보',    0, '국세·지방세 체납 제외 조항. 납세증명서로만 확인된다 — 규칙이 단정하지 않는다.', null, false),
  ('참여제한_제외',       '정보',    0, '국가연구개발사업 참여제한 제외 조항. 우리 DB 에 없는 사실이라 확인필요다.', null, false),
  ('제출서류',            '정보',    0, '요구 서류. app.ann_required_docs 와 대조해 준비도를 낸다.', null, false)
on conflict (특징키) do update
  set 종류 = excluded.종류, 가중치 = excluded.가중치, 설명 = excluded.설명,
      회사컬럼 = excluded.회사컬럼, 필수_커버리지 = excluded.필수_커버리지,
      updated_at = now();

-- -----------------------------------------------------------------------------
-- 6. 섀도 대조 뷰 — 규칙 판정을 LLM 판정 옆에 놓는다
--
--    「LLM 없이도 된다」는 주장은 이 뷰에서만 나온다. 지어낸 수치를 쓰지 않는다.
--    LLM 이 이미 판정한 건에만 행이 생긴다(현재 37건).
-- -----------------------------------------------------------------------------
create or replace view app.v_ann_rule_vs_llm as
select
  r.announcement_id,
  a.사업명,
  a.출처,
  r.엔진버전,
  r.판정                                  as 규칙_판정,
  r.점수                                  as 규칙_점수,
  r.확신도                                as 규칙_확신도,
  r.커버리지,
  e.확정_판정                             as llm_판정,
  (e.ai_제안 ->> '점수')::int             as llm_점수,
  e.ai_확신도                             as llm_확신도,
  (r.판정 = e.확정_판정)                  as 판정일치,
  abs(r.점수 - coalesce((e.ai_제안 ->> '점수')::int, r.점수)) as 점수차,
  e.정정여부                              as 사람정정,
  r.llm_호출
from app.ann_rule_scores r
join app.announcements a          on a.id = r.announcement_id
join app.eligibility_decisions e  on e.announcement_id = r.announcement_id;

comment on view app.v_ann_rule_vs_llm is
  '규칙 판정 vs LLM 판정 섀도 대조. 일치율·점수차의 유일한 근거. '
  'LLM 이 판정한 건에만 행이 생긴다 — 규칙 엔진의 커버리지가 더 넓어서 대부분의 공고는 여기 없다.';

-- -----------------------------------------------------------------------------
-- 7. 커버리지 지표 뷰 — 「836건 중 규칙만으로 몇 건, LLM 호출 몇 회」
-- -----------------------------------------------------------------------------
create or replace view app.v_ann_rule_coverage as
select
  r.엔진버전,
  count(*)                                                  as 판정건수,
  count(*) filter (where r.llm_호출 = 0)                     as llm없이_판정,
  sum(r.llm_호출)                                            as llm_호출_합,
  count(*) filter (where r.판정 = '가능')                    as 가능,
  count(*) filter (where r.판정 = '불가')                    as 불가,
  count(*) filter (where r.판정 = '확인필요')                as 확인필요,
  count(*) filter (where r.판정 = '요건미확인')              as 요건미확인,
  (select count(*) from app.announcements)                   as 전체공고,
  round(avg(r.커버리지), 3)                                  as 평균커버리지
from app.ann_rule_scores r
group by r.엔진버전;

comment on view app.v_ann_rule_coverage is
  '규칙 엔진 커버리지 지표. 화면·챗봇이 「전체 N건 중 LLM 호출 0회로 M건 판정」을 여기서 읽는다. '
  '요건미확인은 실패가 아니라 정직한 상태다 — 본문을 확보하면 판정된다.';

-- -----------------------------------------------------------------------------
-- 8. 권한 — 객체 단위만. 롤 DDL 은 하지 않는다(예전에 클러스터가 25초 멈췄다)
-- -----------------------------------------------------------------------------
alter table app.ann_features         enable row level security;
alter table app.ann_rule_scores      enable row level security;
alter table app.ann_feature_answers  enable row level security;
alter table app.extraction_lexicon   enable row level security;
alter table app.scoring_weights      enable row level security;

drop policy if exists authenticated_read_ann_features on app.ann_features;
create policy authenticated_read_ann_features on app.ann_features
  for select to authenticated using (true);

drop policy if exists authenticated_read_ann_rule_scores on app.ann_rule_scores;
create policy authenticated_read_ann_rule_scores on app.ann_rule_scores
  for select to authenticated using (true);

drop policy if exists authenticated_read_ann_feature_answers on app.ann_feature_answers;
create policy authenticated_read_ann_feature_answers on app.ann_feature_answers
  for select to authenticated using (true);

drop policy if exists authenticated_read_extraction_lexicon on app.extraction_lexicon;
create policy authenticated_read_extraction_lexicon on app.extraction_lexicon
  for select to authenticated using (true);

drop policy if exists authenticated_read_scoring_weights on app.scoring_weights;
create policy authenticated_read_scoring_weights on app.scoring_weights
  for select to authenticated using (true);

grant select on app.ann_features, app.ann_rule_scores, app.ann_feature_answers,
                app.extraction_lexicon, app.scoring_weights,
                app.v_ann_rule_vs_llm, app.v_ann_rule_coverage
  to authenticated;

grant all on app.ann_features, app.ann_rule_scores, app.ann_feature_answers,
              app.extraction_lexicon, app.scoring_weights
  to service_role;
grant select on app.v_ann_rule_vs_llm, app.v_ann_rule_coverage to service_role;

-- ⚠ "all sequences in schema app" 로 한 번에 주려다 전에 걸렸다 — app 스키마의 다른
--   시퀀스 소유자가 rnd_dev 가 아니라 권한 없음으로 트랜잭션 전체가 롤백됐다(91_ 참조).
--   이 파일이 만든 시퀀스만 targeted 로 준다.
grant usage, select on
  app.ann_features_id_seq,
  app.ann_rule_scores_id_seq,
  app.ann_feature_answers_id_seq,
  app.extraction_lexicon_id_seq
  to service_role;

commit;

-- PostgREST 가 새 테이블·뷰를 보게 한다. 빠뜨리면 404 가 나고 권한 문제로 오해한다.
notify pgrst, 'reload schema';

-- =============================================================================
-- 되돌리기 — 새로 만든 것만 지운다. 기존 테이블은 애초에 건드리지 않았다.
-- =============================================================================
-- begin;
-- drop view  if exists app.v_ann_rule_coverage;
-- drop view  if exists app.v_ann_rule_vs_llm;
-- drop table if exists app.extraction_lexicon;
-- drop table if exists app.ann_feature_answers;
-- drop table if exists app.ann_rule_scores;
-- drop table if exists app.ann_features;
-- drop table if exists app.scoring_weights;
-- commit;
-- notify pgrst, 'reload schema';
