-- =============================================================================
-- 103_doc_read_learning.sql — 증빙 판독 결과 + 서식 판별 학습 루프
--
--   왜: `app.decisions` 는 **비목** 정정 이력을 이미 담는다(expense_id 단위).
--       그런데 **서식 판별**(견적서/거래명세서/검수조서/세금계산서…) 축에는
--       AI 제안·사람 확정을 적는 자리가 없다. `app.project_evidence_files` 에는
--       서식 컬럼도, 추출한 본문 텍스트도 없다. 그래서 **학습이 불가능하다.**
--
--   실측 근거 (2026-09-03, 사내 실데이터 772파일, LLM 0회):
--     · 서식 판별 규칙기반 92.8%  ->  학습모델 97.4%   (689건·13서식, 건 단위 그룹분리)
--     · 학습곡선 단조증가: 48건 81.5% -> 171건 92.9%(규칙기반 추월) -> 492건 97.4%
--     · 정정우선 학습(가중 x3)이 무작위보다 +2.6p (같은 라벨링 예산, 초반 +3.6p)
--     · PDF 508개 중 241개(47.4%)가 스캔본 -> OCR 텍스트도 학습 피처로 넣어야 한다
--     상세: 01. 사전준비/프로토타입/ocr_selfmodel/결과_20260903.md
--
--   설계 원칙
--     · **ALTER 하지 않는다.** 기존 테이블은 supabase_admin 소유라 막힌다. 신규 테이블만.
--     · 판독 결과는 파일당 1행(갱신), 정정 이력은 append-only(별 테이블).
--       `app.decisions` 와 같은 모양으로 맞춘다 — 정정사유_유형 4종도 동일하게.
--     · 사업자번호는 가중 모듈러 검증(1·3·7·1·3·7·1·3·5 + 9번째x5의 십의자리).
--       실측: 1자리 오독 검출률 100%(3060/3060), 2자리 88.9%,
--             무작위 10자리 통과율 9.99% -> **식별용이 아니라 검출용이다.**
--             교정 후보는 정확히 10개로 줄고, 유일 확정은 vendors 조회가 한다.
--
--   적용: cd /web/rnd && ./db/psql.sh -f db/103_doc_read_learning.sql
--   되돌리기: 파일 맨 아래
-- =============================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1) 사업자번호 검증 함수 — 합이 아니다. 가중 모듈러 + 검증자리다.
-- ---------------------------------------------------------------------------
create or replace function app.brn_valid(p text)
returns boolean
language plpgsql
immutable
as $$
declare
  s text := regexp_replace(coalesce(p, ''), '[^0-9]', '', 'g');
  w int[] := array[1,3,7,1,3,7,1,3,5];
  acc int := 0;
  i int;
begin
  if length(s) <> 10 then
    return false;
  end if;
  for i in 1..9 loop
    acc := acc + w[i] * (substr(s, i, 1))::int;
  end loop;
  -- 9번째 자리는 5를 곱한 값의 십의 자리를 한 번 더 더한다
  acc := acc + ((substr(s, 9, 1))::int * 5) / 10;
  return ((10 - (acc % 10)) % 10) = (substr(s, 10, 1))::int;
end;
$$;

comment on function app.brn_valid(text) is
  '사업자등록번호 검증. 가중치 1,3,7,1,3,7,1,3,5 + 9번째x5의 십의자리. '
  '1자리 오독은 100% 검출되지만 무작위 10자리도 약 10%가 통과한다 — 검출용이며 식별용이 아니다.';

-- ---------------------------------------------------------------------------
-- 2) 판독 결과 — 증빙 파일 1건당 1행
-- ---------------------------------------------------------------------------
create table if not exists app.evidence_doc_reads (
  id             bigint generated by default as identity primary key,
  파일_id        bigint not null unique
                   references app.project_evidence_files(id) on delete cascade,

  -- 추출 경로. 실측: native 52.4% / ocr 47.4%
  추출_경로      text not null
                   check (추출_경로 in ('native', 'ocr', 'none')),
  추출_도구      text,                      -- pypdf | olefile | openpyxl | tesseract
  ocr_psm        text,                      -- 실측: 표 서식은 psm 4 (psm 6 대비 50% -> 87.6%)
  ocr_확신도     numeric(5,2),              -- tesseract 평균 word conf
  문자수         int,
  본문텍스트     text,                      -- ★ 학습 피처. 실데이터다 — 공개 URL 금지

  -- AI 서식 판별
  ai_서식        text,
  ai_확신도      numeric(4,3),
  ai_출처        text check (ai_출처 in ('rule', 'model', 'llm')),
  ai_근거        jsonb,                     -- rule: 매칭 스니펫 / model: 상위 토큰·최근접 이웃
  모델_버전      int,

  -- 사람 확정
  확정_서식      text,
  서식_정정여부  boolean not null default false,
  확정자         text,
  확정_시각      timestamptz,

  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  -- 확정했으면 확정자가 있어야 한다
  constraint 확정하면_확정자_필수
    check (확정_서식 is null or (확정자 is not null and 확정_시각 is not null))
);

create index if not exists evidence_doc_reads_서식_idx
  on app.evidence_doc_reads (확정_서식, created_at desc);
create index if not exists evidence_doc_reads_학습_idx
  on app.evidence_doc_reads (추출_경로, 확정_서식)
  where 확정_서식 is not null;
create index if not exists evidence_doc_reads_미확정_idx
  on app.evidence_doc_reads (ai_확신도)
  where 확정_서식 is null;

comment on table app.evidence_doc_reads is
  '증빙 파일 판독 결과. 본문텍스트가 서식 판별 모델의 학습 피처다. '
  'OCR 텍스트도 같이 들어가므로 OCR 개선이 그대로 모델 개선으로 이어진다.';

-- ---------------------------------------------------------------------------
-- 3) 서식 판별 정정 이력 — append-only. app.decisions 와 같은 모양
-- ---------------------------------------------------------------------------
create table if not exists app.doc_read_decisions (
  id             bigint generated by default as identity primary key,
  판독_id        bigint not null
                   references app.evidence_doc_reads(id) on delete cascade,
  ai_제안        jsonb not null,            -- {서식, 확신도, 출처, 근거}
  확정_서식      text not null,
  정정여부       boolean not null default false,
  정정사유       text,
  정정사유_유형  text,
  확정자         text,
  created_at     timestamptz not null default now(),

  -- app.decisions 와 동일한 4종으로 맞춘다
  constraint doc_read_decisions_정정사유_유형_chk
    check (정정사유_유형 is null or 정정사유_유형 in ('관행','해석','과제특수','판독오류')),
  constraint doc_read_decisions_정정하면_유형_필수
    check (정정여부 = false or 정정사유_유형 is not null),
  constraint doc_read_decisions_정정하면_사유_필수
    check (정정여부 = false
           or (정정사유 is not null and length(btrim(정정사유)) > 0))
);

create index if not exists doc_read_decisions_판독_idx
  on app.doc_read_decisions (판독_id);
create index if not exists doc_read_decisions_정정_idx
  on app.doc_read_decisions (정정여부, created_at desc) where 정정여부;
create index if not exists doc_read_decisions_정정유형_idx
  on app.doc_read_decisions (정정사유_유형, created_at desc) where 정정여부;

comment on table app.doc_read_decisions is
  '서식 판별 정정 이력. 재학습에서 정정여부=true 인 행이 가중치를 더 받는다 '
  '(실측: 가중 x3 정정우선이 무작위보다 +2.6p).';

-- ---------------------------------------------------------------------------
-- 4) 모델 버전 — 무엇으로 학습했고 얼마나 맞았는지
-- ---------------------------------------------------------------------------
create table if not exists app.model_versions (
  id             int generated by default as identity primary key,
  과제           text not null check (과제 in ('doctype', 'bimok')),
  학습시각       timestamptz not null default now(),
  학습건수       int not null,
  정정건수       int not null default 0,
  정정가중       numeric(4,2) not null default 3.0,
  tau            numeric(4,3),              -- 자동확정 임계값. 실측 비목 0.70
  지표           jsonb not null,            -- 그룹분리 정확도·클래스별·혼동행렬
  artifact_path  text not null,             -- joblib. 수백 KB
  만든이         text,
  사용중         boolean not null default false
);

-- 과제별로 사용중 모델은 하나뿐
create unique index if not exists model_versions_사용중_uq
  on app.model_versions (과제) where 사용중;

comment on table app.model_versions is
  '자체 모델 버전. 지표는 반드시 그룹분리 조건으로 적는다 — '
  '거래처를 피처에 넣은 LOO 는 95.8%, 거래처 분리는 83.1%였다. 낙관값을 적으면 안 된다.';

-- ---------------------------------------------------------------------------
-- 5) 학습셋 뷰 — 재학습은 이것만 읽는다
--    sample_weight = 1 + (정정가중 - 1) * 정정여부
-- ---------------------------------------------------------------------------
create or replace view app.v_trainset_doctype as
select r.id,
       r.본문텍스트                                as x,
       r.확정_서식                                 as y,
       coalesce(f.집행_id::text, 'file:' || r.id)  as grp,   -- 같은 건의 문서가 갈리면 누출
       r.추출_경로,
       coalesce(bool_or(d.정정여부), false)        as 정정여부,
       max(d.created_at)                           as 최종확정
  from app.evidence_doc_reads r
  join app.project_evidence_files f on f.id = r.파일_id
  left join app.doc_read_decisions d on d.판독_id = r.id
 where r.확정_서식 is not null
   and r.본문텍스트 is not null
   and coalesce(r.문자수, 0) >= 20
 group by r.id, r.본문텍스트, r.확정_서식, f.집행_id, r.추출_경로;

comment on view app.v_trainset_doctype is
  '서식 판별 학습셋. grp 는 집행_id — 같은 건의 문서 8개가 학습/검증에 갈리면 누출된다.';

-- ---------------------------------------------------------------------------
-- 6) 거래처 -> 비목 조회표
--    실측: 재등장 거래처 36.4% 를 정확도 100%(28/28) 로 확정했다. 모델·LLM 을 안 부른다.
--    순도가 깨진 거래처(비목이 둘 이상)는 자동확정에서 뺀다.
-- ---------------------------------------------------------------------------
-- 키는 거래처명이 아니라 사업자번호다. 상호는 표기가 흔들리고(주/(주)/주식회사) 번호는 안 흔들린다.
create or replace view app.v_vendor_bimok as
select e.거래처_사업자번호                          as 사업자번호,
       max(e.거래처)                                as 거래처,
       app.brn_valid(e.거래처_사업자번호)           as 번호검증,
       mode() within group (order by d.확정_비목)   as 비목,
       mode() within group (order by d.확정_세부항목) as 세부항목,
       count(*)                                     as 확정건수,
       count(distinct d.확정_비목)                  as 비목종류수,
       count(*) filter (where d.정정여부)           as 정정건수,
       max(d.created_at)                            as 최종확정
  from app.decisions d
  join app.expenses e on e.id = d.expense_id
 where e.거래처_사업자번호 is not null
 group by e.거래처_사업자번호;

comment on view app.v_vendor_bimok is
  '거래처별 확정 비목. 재등장 거래처는 여기 조회 한 번으로 확정된다 — 모델·LLM 을 안 부른다 '
  '(실측 커버리지 36.4%, 정확도 100% 28/28). '
  '비목종류수 > 1 인 거래처는 자동확정에서 제외한다 — 순도가 깨졌다.';

commit;

notify pgrst, 'reload schema';

-- =============================================================================
-- 검증
-- =============================================================================
-- 유효한 실제 형태 / 검증자리 틀린 것 / 자리수 부족
--   select app.brn_valid('1234567890'), app.brn_valid('123-45-6789'), app.brn_valid(null);
-- 거래처 마스터에 검증 실패하는 번호가 있는지
--   select count(*) filter (where not app.brn_valid(사업자번호)) as 검증실패,
--          count(*) filter (where 사업자번호 is not null)        as 번호보유
--     from app.vendors;

-- =============================================================================
-- 되돌리기
-- =============================================================================
-- begin;
-- drop view if exists app.v_vendor_bimok;
-- drop view if exists app.v_trainset_doctype;
-- drop table if exists app.model_versions;
-- drop table if exists app.doc_read_decisions;
-- drop table if exists app.evidence_doc_reads;
-- drop function if exists app.brn_valid(text);
-- commit;
-- notify pgrst, 'reload schema';
