-- =============================================================================
-- 107_judgment_semantic.sql — 사람 판정+코멘트를 의미로 검색할 수 있게 쌓는다
--
--   왜: 오늘 만든 extraction_lexicon(db/102_)은 문구가 글자 그대로 같아야 걸린다.
--   "일반음식점을 영업 중인 자"를 배웠어도 "이미용업소는요"는 못 잡는다 — 같은
--   뜻인데 글자가 다르다. 사용자 질문(2026-09-04): "각 사업별 직접판정하고
--   코멘트 작성하면 자연어 처리해서 학습하는 구조로 가능?" — 로컬 임베딩 모델로
--   가능하다(F:\solverton\insight_engine.py 의 classify_new_comment() 와 같은 방식).
--
--   ⚠ 벡터 DB 를 넣지 않는다(CLAUDE.md §6) — pgvector 확장을 쓰지 않고 임베딩을
--   평범한 jsonb 배열로 저장한다. 유사도 계산은 파이썬에서 코사인 유사도로 직접
--   한다 — 이 규모(수백~수천 건)에서 인덱스 없이도 충분히 빠르다.
--
--   무거운 의존성(torch, sentence-transformers)은 이 테이블을 쓰는 봇 프로세스에
--   안 들어간다 — pdf_extract.py 와 같은 패턴으로 격리된 venv(/rnd/bot/venv-embed)
--   의 독립 스크립트(embed_cli.py)를 subprocess 로만 부른다.
--
--   설계 원칙: 추가만 한다. 기존 테이블은 안 건드린다.
--   적용:     cd /web/rnd && ./db/psql.sh -f db/107_judgment_semantic.sql
--   되돌리기: 파일 맨 아래
-- =============================================================================

begin;

create table if not exists app.judgment_semantic (
  id               bigint generated by default as identity primary key,
  announcement_id  bigint references app.announcements(id) on delete cascade,
  텍스트           text not null,        -- 판정 근거가 된 문장(근거문장 인용 또는 사람 코멘트)
  임베딩           jsonb not null,       -- float[384] (paraphrase-multilingual-MiniLM-L12-v2)
  임베딩모델       text not null default 'paraphrase-multilingual-MiniLM-L12-v2',
  판정             text not null,        -- 가능 | 불가 | 확인필요 | 요건미확인 | 해당없음
  특징키           text,                 -- 있으면 어느 게이트/가산에 대한 판단인지(예: 창업업력_제한)
  사유             text,                 -- 사람이 남긴 코멘트
  답변자           text not null,
  created_at       timestamptz not null default now(),
  constraint chk_judgment_판정
    check (판정 in ('가능', '불가', '확인필요', '요건미확인', '해당없음'))
);

create index if not exists idx_judgsem_공고 on app.judgment_semantic (announcement_id);

comment on table app.judgment_semantic is
  '사람이 판정+코멘트를 남기면 임베딩해서 쌓는다. 다음 공고를 볼 때 문구가 달라도 '
  '의미가 비슷하면(코사인 유사도) 과거 판정을 참고 사례로 보여준다 — 정답을 대신 '
  '내리지 않는다. 판단 우선순위 1층(정정 이력)을 문자열 일치 너머로 확장한 것이다.';
comment on column app.judgment_semantic.임베딩 is
  'jsonb 배열. pgvector 안 쓴다(CLAUDE.md §6, "벡터 DB" 제외) — 유사도는 파이썬에서 '
  '코사인 유사도로 계산한다. 이 규모에선 인덱스 없이도 충분하다.';

alter table app.judgment_semantic enable row level security;

drop policy if exists authenticated_read_judgment_semantic on app.judgment_semantic;
create policy authenticated_read_judgment_semantic on app.judgment_semantic
  for select to authenticated using (true);

grant select on app.judgment_semantic to authenticated;
grant all on app.judgment_semantic to service_role;
grant usage, select on app.judgment_semantic_id_seq to service_role;

commit;

notify pgrst, 'reload schema';

-- =============================================================================
-- 되돌리기
-- =============================================================================
-- drop table if exists app.judgment_semantic;
-- notify pgrst, 'reload schema';
