-- =============================================================================
-- 107_llm_usage.sql — LLM 호출 토큰·비용 실측 적재
--
--   왜: 「LLM 의존도를 낮췄다」를 주장하려면 **얼마나 안 썼는지**를 숫자로 대야 한다.
--       지금은 로컬이 처리한 건과 LLM 이 처리한 건이 섞여 있는데 계량이 안 된다.
--       claude 헤드리스는 `--output-format json` 으로 usage 를 그대로 돌려준다.
--       그걸 호출마다 쌓아 「건당 토큰·비용」과 「로컬 처리 비율」을 실측한다.
--
--   적용: cd /web/rnd && ./db/psql.sh -f db/107_llm_usage.sql
--   되돌리기: 파일 맨 아래
-- =============================================================================

begin;

create table if not exists app.llm_usage (
  id                bigint generated by default as identity primary key,
  단계              text not null,          -- read_evidence | classify | chat ...
  모델              text,
  성공              boolean not null default true,
  사유              text,                   -- 실패 시 원인

  입력토큰          int,
  출력토큰          int,
  캐시생성토큰      int,
  캐시읽기토큰      int,
  총토큰            int,
  비용_usd          numeric(10, 6),
  소요초            numeric(8, 2),
  턴수              int,

  expense_id        bigint,                 -- 어느 집행 건이었나 (있으면)
  파일명            text,
  created_at        timestamptz not null default now()
);

create index if not exists llm_usage_단계_idx on app.llm_usage (단계, created_at desc);
create index if not exists llm_usage_실패_idx on app.llm_usage (성공, created_at desc)
  where not 성공;

comment on table app.llm_usage is
  'LLM 호출 실측. 로컬 경로가 처리한 건은 여기 행이 생기지 않는다 — '
  '행이 없는 것 자체가 「LLM 을 안 썼다」는 증거다.';

-- 한눈에 보는 집계 — 발표 지표로 그대로 쓴다
create or replace view app.v_llm_usage_summary as
select 단계,
       count(*)                                   as 호출수,
       count(*) filter (where not 성공)            as 실패수,
       round(avg(총토큰))                          as 평균토큰,
       sum(총토큰)                                 as 총토큰,
       round(avg(비용_usd)::numeric, 5)            as 평균비용_usd,
       round(sum(비용_usd)::numeric, 4)            as 총비용_usd,
       round(avg(소요초)::numeric, 1)              as 평균초
  from app.llm_usage
 group by 단계
 order by 호출수 desc;

commit;

notify pgrst, 'reload schema';

-- =============================================================================
-- 되돌리기
-- =============================================================================
-- begin;
-- drop view if exists app.v_llm_usage_summary;
-- drop table if exists app.llm_usage;
-- commit;
-- notify pgrst, 'reload schema';
