-- =============================================================================
-- 115_notifications.sql — 시스템이 먼저 말한 것을 남긴다
--
--   왜: 지금까지 봇은 **사람이 올린 것에 답만** 했다. 참가 계획서 문항3 3단계와
--   문항4 ①④가 약속한 「기한이 임박한 건을 Slack 으로 미리 알린다」에 해당하는
--   경로가 코드에 없었다(2026-09-04 점검: crontab 비어 있고 rnd 관련 systemd
--   타이머도 없다). bot/notify.py 가 그 경로다.
--
--   이 테이블이 필요한 이유는 **같은 말을 두 번 하지 않기 위해서**다.
--   타이머는 재시작·수동 실행으로 하루에 여러 번 돌 수 있다. 그때마다 같은
--   알림이 채널에 쌓이면 사람이 알림을 끈다 — 그러면 기능이 죽은 것과 같다.
--   `키` 에 (종류·대상·날짜)를 넣고 unique 로 막는다. 막는 일을 코드가 아니라
--   DB 가 한다 — 동시에 두 번 떠도 한 번만 나간다.
--
--   보낸 것을 남겨 두면 「그때 알림 갔었나?」에 답할 수 있다. 알림도 기록이다.
--
--   설계 원칙: 추가만 한다. 기존 테이블·뷰는 안 건드린다.
--   적용:     cd /web/rnd && ./db/psql.sh -f db/115_notifications.sql
--   되돌리기: 파일 맨 아래
-- =============================================================================

begin;

create table if not exists app.notifications (
  id         bigint generated by default as identity primary key,
  키         text not null unique,   -- 종류:참조:날짜. 하루 한 번을 DB 가 보장한다
  종류       text not null,          -- 신청마감 | 결과등록 | 관심공고 | 보고기한 | 서류만료 | 정산위험 | 월정산 | 주간브리핑
  참조종류   text,                   -- 사업 | 공고 | 집행 | 서류 | (없음)
  참조_id    text,                   -- 숫자 id 도 코드도 담을 수 있게 text
  제목       text not null,
  본문       text,
  채널       text,
  slack_ts   text,                   -- 실제로 나간 메시지. 못 보냈으면 null
  발송시각   timestamptz not null default now()
);

create index if not exists idx_notifications_종류
  on app.notifications (종류, 발송시각 desc);

comment on table app.notifications is
  '시스템이 사람에게 먼저 건넨 말의 이력. bot/notify.py 가 쓴다. '
  '`키` 의 unique 제약이 「하루 한 번」을 보장한다 — 타이머가 여러 번 돌아도 안전하다. '
  '⚠ 판정은 여기 없다. 무엇을 알릴지는 전부 계산으로 정하고(금액·기한은 AI 가 아니다) '
  '이 테이블은 보낸 사실만 기록한다.';
comment on column app.notifications.키 is
  '예: 신청마감:project:78:2026-09-04. 날짜를 넣으므로 내일은 다시 나간다 — '
  '「결과 등록 전까지 지속 리마인드」(계획서 문항4①)가 이 설계로 성립한다.';
comment on column app.notifications.slack_ts is
  'null 이면 계산은 됐는데 발송이 실패한 것이다. 조용히 안 나간 것과 구분된다.';

alter table app.notifications enable row level security;

drop policy if exists authenticated_read_notifications on app.notifications;
create policy authenticated_read_notifications on app.notifications
  for select to authenticated using (true);

grant select on app.notifications to authenticated;
grant select on app.notifications to rnd_mcp;
grant all    on app.notifications to service_role;
grant usage, select on app.notifications_id_seq to service_role;

commit;

notify pgrst, 'reload schema';

-- =============================================================================
-- 되돌리기
-- =============================================================================
-- drop table if exists app.notifications;
-- notify pgrst, 'reload schema';
