-- =============================================================================
-- 91_ann_summary.sql — 공고 상세 요약: 지원분야·지원대상·지원규모·접수방법·문의처
--
--   왜: 공고 탐색에서 사업명을 누르면 상세 패널이 뜨는데, 지금 announcements 에는
--   본문(원문 텍스트)만 있고 구조화된 요약이 없다. 매번 본문을 화면에서 그대로
--   보여주면 사람이 다시 읽어야 한다 — 그게 케이오시 현안 1번("건당 2~4시간, 엑셀
--   수기 정리")이 반복되는 것이다. LLM 이 본문에서 뽑고, 근거가 없으면 null 로 둔다
--   (지어내지 않는다 — §6 설계 원칙 5번).
--
--   1개 공고 = 1행. UNIQUE(announcement_id) 로 강제한다 — 재추출은 upsert.
--
--   설계 원칙: 추가만 한다. 기존 테이블은 안 건드린다.
--   적용: db/psql.sh -f db/91_ann_summary.sql
--   되돌리기: 파일 맨 아래 블록
-- =============================================================================

create table if not exists app.ann_summary (
  id               bigint generated by default as identity primary key,
  announcement_id  bigint not null references app.announcements(id) on delete cascade,
  지원분야         text,
  지원대상         text,
  지원규모         text,
  접수방법         text,
  문의처           text,
  사업요약         text,
  ai_확신도        numeric(4,3),
  created_at       timestamptz not null default now(),
  unique (announcement_id)
);

comment on table app.ann_summary is
  '공고 본문에서 LLM(claude -p 헤드리스)이 뽑은 구조화 요약. 공고문에 없는 값은 null — 지어내지 않는다.';

alter table app.ann_summary enable row level security;

drop policy if exists authenticated_read_ann_summary on app.ann_summary;
create policy authenticated_read_ann_summary on app.ann_summary
  for select to authenticated using (true);

grant select on app.ann_summary to authenticated;
grant all on app.ann_summary to service_role;
-- ⚠ "grant ... on all sequences in schema app" 로 한 번에 하려다 걸림 — app 스키마의
-- 다른 시퀀스(watchlist_id_seq 등) 소유자가 rnd_dev 가 아니라 권한 없음 에러로
-- 트랜잭션 전체가 롤백됐다(실측). 이 테이블의 시퀀스만 targeted 로 준다.
grant usage, select on app.ann_summary_id_seq to service_role;

notify pgrst, 'reload schema';

-- =============================================================================
-- 되돌리기
-- =============================================================================
-- drop table if exists app.ann_summary;
-- notify pgrst, 'reload schema';
